### ISSUE TITLE
Question about Quill.js Delta format

### ISSUE THREAD

**Issue by Alspb** [fleather-editor/fleather#310]
Why does Delta format used in the editor differ a bit from the one described in [Quill.js Delta](https://quilljs.com/docs/delta)?
For example, bold is denoted as "b", not "bold". Color set sometimes looks unusual too, e.g., "4278237952" (see fleather/example/assets/welcome.json).

**Comment by Amir-P** [comment]
> Why does Delta format used in the editor differ a bit from the one described in [Quill.js Delta](https://quilljs.com/docs/delta)?

Fleather is based on [Zefyr](https://github.com/memspace/zefyr), where these differences are coming from. If I were to rewrite it, I would've probably stick to the quill.js standards.

> For example, bold is denoted as "b", not "bold". Color set sometimes looks unusual too, e.g., "4278237952" (see fleather/example/assets/welcome.json).

Support for colors is added in Fleather by @amantoux and I think it makes sense to use the bytes representation since that's how it's handled in `Color` from `dart:ui`.

**Comment by amantoux** [comment]
Closing as not activity for 3 weeks
Feel free to re-open
