### ISSUE TITLE
Change Url Source

### ISSUE THREAD

**Issue by pastordee** [fleather-editor/fleather#334]
Hi guys, I want to embed an image but before I save I want to upload it to my server first then insert or change the embeddable object link in the Url source section. Can someone please show me how to change the URL source?  

Thanks

**Comment by ShawnWong520** [comment]
like this:
{
    "insert": {
      "_type": "image",
      "_inline": true,
      "source": "images/breeze.jpg",
      "orientation": "landscape",
      "source_type": "assets"
    }
  },
  {
    "insert": {
      "_type": "image",
      "_inline": true,
      "source": "https://d1zt7gd2qg83yd.cloudfront.net/uploads/images/topics/EtkrvZ7KMf3SDTIXMS1eggclCmQCbF1rOHsX9BR1.jpg",
      "source_type": "url"
    }
  },

**Comment by Amir-P** [comment]
Hi @pastordee , I would not add the image into the editor while it's being updated but if that's what you really want, I would insert a placeholder image embed without any sources, but with an ID or name property so that I can later find and update it.
After the image is uploaded, I would find the embed with that ID or name, remove it, and replace with the real image. Let me know if you need further information.

**Comment by Amir-P** [comment]
Closing as there were no activities.
